# Generated by Django 3.2.17 on 2023-02-22 00:03

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Surname', models.CharField(blank=True, max_length=50, null=True)),
                ('About', models.TextField(blank=True, max_length=200, null=True)),
                ('Profile_Image', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/seanf316/image/upload/v1677023649/default-profile_fb2lrf_xbtzxc.jpg', max_length=255, verbose_name='image')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
