# Generated by Django 3.2.17 on 2023-02-22 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='About',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='First_Name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Profile_Image',
            new_name='profile_image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Surname',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
    ]
