# Generated by Django 3.2.17 on 2023-03-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20230301_2222'),
        ('profiles', '0004_profile_to_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reviewed',
            field=models.ManyToManyField(blank=True, related_name='reviewed', to='movie.Movie'),
        ),
    ]
