# Generated by Django 3.2.17 on 2023-03-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20230310_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, default='I love Cinema|Go', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='director',
            field=models.CharField(blank=True, default="Who's your favourite Director?", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fav_movie',
            field=models.CharField(blank=True, default="What's your favourite Movie?", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(blank=True, default='Firstname', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, default='Surname', max_length=50, null=True),
        ),
    ]
