# Generated by Django 3.2.17 on 2023-03-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20230310_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav_actor',
            field=models.CharField(blank=True, default="Who's your favourite Actor?", max_length=50, null=True),
        ),
    ]
