# Generated by Django 3.2.17 on 2023-03-22 00:09

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_fav_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=djrichtextfield.models.RichTextField(blank=True, default='I love Cinema|Go', max_length=200, null=True),
        ),
    ]
