# Generated by Django 3.2.17 on 2023-03-05 00:16

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=djrichtextfield.models.RichTextField(blank=True, max_length=2500, null=True),
        ),
    ]
