# Generated by Django 3.2.17 on 2023-03-22 01:08

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=djrichtextfield.models.RichTextField(max_length=2500, null=True),
        ),
    ]
