# Generated by Django 3.2.17 on 2023-03-30 13:43

import django.core.validators
from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=djrichtextfield.models.RichTextField(max_length=507, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=djrichtextfield.models.RichTextField(null=True, validators=[django.core.validators.MaxLengthValidator(2507)]),
        ),
    ]
