# Generated by Django 3.2.17 on 2023-03-30 21:32

import django.core.validators
from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20230330_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=djrichtextfield.models.RichTextField(default='Enter Review here...', validators=[django.core.validators.MaxLengthValidator(507)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=djrichtextfield.models.RichTextField(default='Enter Review here...', validators=[django.core.validators.MaxLengthValidator(2507)]),
        ),
    ]
