# Generated by Django 3.2.17 on 2023-03-30 21:59

import django.core.validators
from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20230330_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=djrichtextfield.models.RichTextField(default='Enter Comment here...', validators=[django.core.validators.MaxLengthValidator(507)]),
        ),
    ]
