# Generated by Django 3.2.17 on 2023-02-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('Slug', models.SlugField(max_length=200, unique=True)),
                ('Overview', models.TextField(blank=True)),
                ('Director', models.CharField(max_length=50)),
                ('Released', models.CharField(blank=True, max_length=25)),
                ('Runtime', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
