# Generated by Django 3.2.17 on 2023-02-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='MovieId',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
