# Generated by Django 3.2.17 on 2023-02-20 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_movie_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['Name']},
        ),
    ]
