# Generated by Django 3.2.17 on 2023-02-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Director',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
