# Generated by Django 3.2.17 on 2023-03-01 22:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20230221_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Backdrop',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/seanf316/image/upload/v1677179557/Cinema-Go/no_backdrop_ptm59z.webp', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='movie',
            name='Poster',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/seanf316/image/upload/v1677179557/Cinema-Go/no_poster_uqgcl9.webp', max_length=255, verbose_name='image'),
        ),
    ]
