# Generated by Django 3.2.17 on 2023-03-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20230301_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Backdrop',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Poster',
        ),
    ]
