# Generated by Django 3.2.17 on 2023-05-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20230302_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='MovieId',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
